server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eplms-apigateway-service
  cloud:
    gateway:
      routes:
        - id: eplms-master-service
          uri: lb://eplms-master-service  
          predicates:
            - Path=/devices/**
        - id: eplms-master-service
          uri: lb://eplms-master-service
          predicates:
            - Path=/departments/**